# Generated by Django 6.0.4 on 2026-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('channel_title', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('subscriber_count', models.PositiveBigIntegerField(default=0)),
                ('video_type', models.CharField(default='video', max_length=16)),
                ('watched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
    ]
