# Generated by Django 6.0.4 on 2026-07-16 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_watchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='video_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'video_id')},
        ),
    ]
