# Generated by Django 6.0.4 on 2026-07-17 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0004_favoritelist_favoritevideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritelist',
            options={'ordering': ['index']},
        ),
        migrations.RenameField(
            model_name='favoritelist',
            old_name='order',
            new_name='index',
        ),
        migrations.AlterUniqueTogether(
            name='favoritelist',
            unique_together={('user', 'index')},
        ),
    ]
