# Generated by Django 6.0.4 on 2026-07-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0005_alter_favoritelist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritevideo',
            name='published_at',
            field=models.CharField(max_length=100),
        ),
    ]
