# Generated by Django 6.0.4 on 2026-08-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0007_remove_searchhistory_max_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritevideo',
            name='published_at',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
