# Generated by Django 6.0.4 on 2026-08-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0008_alter_favoritevideo_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='order',
            field=models.CharField(default='relevance', max_length=32),
        ),
    ]
